USE SAV_UNIVER

--1
CREATE VIEW Преподаватель
AS SELECT TEACHER.TEACHER, TEACHER.TEACHER_NAME, TEACHER.GENDER, TEACHER.PULPIT
FROM TEACHER

--2
CREATE VIEW КоличествоКафедр 
AS
SELECT FACULTY.FACULTY, count(*) [Количество Кафедр]
FROM FACULTY join PULPIT
ON FACULTY.FACULTY = PULPIT.FACULTY
GROUP BY FACULTY.FACULTY

--3
CREATE VIEW Аудитории AS
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛК'

INSERT Аудитории 
VALUES ('424-4', '424-4', 'ЛБ-К')
--4
CREATE VIEW Лекционные_аудитории AS
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛК' WITH CHECK OPTION

INSERT  Лекционные_аудитории
VALUES ('428-4', '428-4', 'ЛК')

--5
CREATE VIEW Дисциплины AS
SELECT TOP(10) SUBJECTS.SUBJECTS_NAME, SUBJECTS.SUBJECTS, SUBJECTS.PULPIT
FROM SUBJECTS
ORDER BY SUBJECTS.SUBJECTS_NAME

--6
ALTER VIEW КоличествоКафедр with schemabinding
		as select FACULTY.FACULTY, count (PULPIT.PULPIT) [count]
		from dbo.FACULTY join dbo.PULPIT
		on FACULTY.FACULTY = PULPIT.FACULTY
		group by FACULTY.FACULTY;