use SAV_UNIVER

--1
select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME
from FACULTY, PULPIT
where FACULTY.FACULTY=PULPIT.FACULTY and
FACULTY.FACULTY in (select PROFESSION.FACULTY FROM PROFESSION
WHERE PROFESSION.PROFESSION_NAME like '%технологии%' or PROFESSION.PROFESSION_NAME like '%технология%')

--2
select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME
from FACULTY
join PULPIT on FACULTY.FACULTY=PULPIT.FACULTY and
FACULTY.FACULTY in (select PROFESSION.FACULTY FROM PROFESSION
WHERE PROFESSION.PROFESSION_NAME like '%технологии%' or PROFESSION.PROFESSION_NAME like '%технология%')

--3
select distinct PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
from PULPIT
join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY
join PROFESSION on FACULTY.FACULTY = PROFESSION.FACULTY
and PROFESSION.PROFESSION_NAME like ('%технологи%')

--4
select AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY
from AUDITORIUM
where AUDITORIUM_CAPACITY = (select top (1) AUDITORIUM_CAPACITY from AUDITORIUM
order by AUDITORIUM_CAPACITY desc)
order by AUDITORIUM_TYPE

--5
 SELECT  FACULTY.FACULTY_NAME  from FACULTY
 Where not exists  (select * from PULPIT
	Where PULPIT.FACULTY = FACULTY.FACULTY)

--6
SELECT top 1 
(select avg(PROGRESS.NOTE) from PROGRESS
  where PROGRESS.SUBJECTS like 'ОАиП' ) [ОАиП],
(select avg(PROGRESS.NOTE) from PROGRESS 
  where PROGRESS.SUBJECTS like 'БД' )[БД],
(select avg(PROGRESS.NOTE) from PROGRESS 
  where PROGRESS.SUBJECTS like 'СУБД' )[СУБД]   From  PROGRESS

--7
select  AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY
from  AUDITORIUM
where AUDITORIUM_CAPACITY <=all (select AUDITORIUM_CAPACITY from AUDITORIUM
where AUDITORIUM.AUDITORIUM_TYPE like '%Б%')
order by AUDITORIUM_TYPE

--8
select  AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY
from  AUDITORIUM
where AUDITORIUM_CAPACITY <=any (select AUDITORIUM_CAPACITY from AUDITORIUM
where AUDITORIUM.AUDITORIUM_TYPE like '%Б%')
order by AUDITORIUM_TYPE