use SAV_UNIVER
--1
select  max(AUDITORIUM.AUDITORIUM_CAPACITY)  [максимальна€ вместимость],
		min(AUDITORIUM.AUDITORIUM_CAPACITY)  [минимальна€ вместимость],
		count(AUDITORIUM.AUDITORIUM_CAPACITY)  [общее кол-во аудиторий],
		sum(AUDITORIUM.AUDITORIUM_CAPACITY)  [сумарна€ вместимость],
		avg(AUDITORIUM.AUDITORIUM_CAPACITY)  [средн€€ вместимость]
from AUDITORIUM
--2
select  AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,
		max(AUDITORIUM.AUDITORIUM_CAPACITY) [максимальна€ вместимость],
		min(AUDITORIUM.AUDITORIUM_CAPACITY)  [минимальна€ вместимость],
		count(AUDITORIUM.AUDITORIUM_CAPACITY)  [общее кол-во аудиторий],
		sum(AUDITORIUM.AUDITORIUM_CAPACITY)  [сумарна€ вместимость],
		avg(AUDITORIUM.AUDITORIUM_CAPACITY)  [средн€€ вместимость]
from AUDITORIUM_TYPE inner join AUDITORIUM on AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE
group by AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
--3
SELECT  *		
from 
(select PROGRESS.NOTE,
count(PROGRESS.NOTE) [кол-во]
from PROGRESS
group by PROGRESS.NOTE) T1
order by 
case
when T1.NOTE >= 4  then 1
else 2
end

--4
select FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE

--5
select FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.SUBJECTS = '—”Ѕƒ' or   PROGRESS.SUBJECTS = 'ќјиѕ'
group by FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE

--6
select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '»ƒиѕ'
group by  rollup( FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS)

--7
select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '»ƒиѕ'
group by  cube( FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS)

--8
select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '»ƒиѕ'
group by  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS
union 
select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '’“и“'
group by  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS


--9
select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '»ƒиѕ'
group by  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS
intersect
select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '’“и“'
group by  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS

--10

select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '»ƒиѕ' or FACULTY.FACULTY = '’“и“'
group by  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS
except
select FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS,
			round(avg(cast(PROGRESS.NOTE as float)),2) [средн€€ отметка]
from FACULTY
join GROUPS on GROUPS.FACULTY= FACULTY.FACULTY
join STUDENT on STUDENT.IDGROUPS = GROUPS.IDGROUPS
join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY = '’“и“'
group by  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECTS

--11
select  count (*) [кол-о студентов], SUBJECTS.SUBJECTS, PROGRESS.NOTE
from SUBJECTS
join PROGRESS on PROGRESS.SUBJECTS = SUBJECTS.SUBJECTS
group by  SUBJECTS.SUBJECTS , PROGRESS.NOTE
having  PROGRESS.NOTE = 8 or PROGRESS.NOTE = 9